### ISSUE TITLE
Obtain SOLID Pods's data

### ISSUE THREAD

**Issue by laura-pb** [Arquisoft/dede_en2b#120]
@pglez82 How can we obtain the pod's information from the backend (Java)? The inrupt library just exists for JS and I haven't been able to find any other library to access them from Java.

**Comment by pglez82** [comment]
Dear Laura. I think I already replied to this by email to Adrián. I have no experience in using Java with solid but maybe you can look for some resources and information here:

https://forum.solidproject.org/t/solid-app-development-in-java-jvm-or-other-ecosystems/221/10
