### ISSUE TITLE
yml workflow 

### ISSUE THREAD

**Issue by DiegoMfer** [Arquisoft/dede_en2b#130]

**Comment by DiegoMfer** [comment]
Helloo, I have a mistake when uncommenting the part of asw2122.yml on line 45, it gives me an syntax error even if the line is commented
![image](https://user-images.githubusercontent.com/79276285/164047138-2f36b68d-1945-4c3a-bc64-a81927266b44.png)

**Comment by pglez82** [comment]
The indentation of the file is wrong. In yaml format indentation determines structure so it is quite important.

**Comment by pglez82** [comment]
I suppose this issue can be closed if this yaml file problem has been solved.
