### ISSUE TITLE
Writing in POD

### ISSUE THREAD

**Issue by UO277653** [Arquisoft/dede_en2b#148]
Hello, @pglez82 , what would be the preferable approach in order to write data in the POD of the user from the application? In case the user does not have an address, or a postal code.

**Comment by pglez82** [comment]
That is something you need to investigate. For any approach you need permissions that need to be asked during the logging process. One approach could be investigate the radarin projects from last year. All groups had to write in the pods for that assignment. After seeing the solutions, maybe the group can decide what to do. 

My only suggestion is to be careful adding this king of non-trivial functionalities a few days from the final release.
