### ISSUE TITLE
Doubt about certain commands in deployment

### ISSUE THREAD

**Issue by UO277653** [Arquisoft/dede_en2b#158]
Hello, @pglez82 , we are in the finishing stages of the application, almost everything works in the way it is supposed to in the deployed app (apart from some small bugs that still have to be solved), but we are not sure about what to do about something in the deployment. In order to have HTTPS access we have to execute "caddy run" in Putty while being connected through SSH to the machine, but this command is one of those that do not finish until you stop it, so if we include it in the workflow of the deployment the machine works and has HTTPS but the deployment never finishes, is there a way to run this in the background so the deployment can be completed? Also, something similar happens with the e2e tests, when running the SpringBoot restapi it does not finish, so the job for the e2e does not finish either.

**Comment by pglez82** [comment]
In Linux you can add & at the end of the command to execute something in the background `caddy run &`.

If that doesn't help it exists also the option to nohup the command. That would be `nohup caddy run &`. Nohup is meant for running processes that are not associated with a terminal. Maybe thats another option.

**Comment by UO277653** [comment]
The command for caddy worked, thank you very much.
