### ISSUE TITLE
Codecov

### ISSUE THREAD

**Issue by DiegoMfer** [Arquisoft/dede_en2b#159]
How can we ignore files in de codecov? I also added the github action in the restapi but it does not take it into account.

**Comment by pglez82** [comment]
Creating a codecov.yml in the root of the repository you can configure this sort of things. More information:

https://docs.codecov.com/docs/ignoring-paths

**Comment by DiegoMfer** [comment]
![image](https://user-images.githubusercontent.com/79276285/166212185-3f326a56-16d4-4f44-acbe-0522dff707c0.png)
It says that the property ignore is not allowed, and there are no sintax errors.

**Comment by pglez82** [comment]
Dear Diego, you are supposed to solve this technical problems, not me. I do not know who is given this syntax errors. This file is read by codecov once you upload it to the repository.

Place the file in the root of your repository and commit it, codecov will analyze it and apply the configuration.

**Comment by DiegoMfer** [comment]
Ok, thanks.

**Comment by DiegoMfer** [comment]
Do I need permision to install Travis on this repository? I am trying to add the codecov for the restapi with a tool called Travis but since only the repositories owned by me are available I suppose I am not allowed to do that.
![image](https://user-images.githubusercontent.com/79276285/166232079-b4891e2e-f03d-467f-90f7-3892e602ab9b.png)

**Comment by pglez82** [comment]
Travis is a continuous integration system, alternative to github actions. In my opinion you should not install that in your repository. If you need to be admin of the repo I can do it but it will be under your responsibility.

**Comment by DiegoMfer** [comment]
Ok i will try other systems

**Comment by UO277653** [comment]
We managed to do this, so I close the issue.
