### ISSUE TITLE
Write documentation section 10: Quality requirements

### ISSUE THREAD

**Issue by laura-pb** [Arquisoft/dede_en2b#20]
Write the tenth part of the documentation: Quality requirements.
This section is divided in two parts: quality tree and quality scenarios.

**Comment by laura-pb** [comment]
I think one quality attribute that we should consider is accessibility. It's very difficult to have a fully accessible application, but we should have it in mind (for example in the use of colours).

**Comment by UO277653** [comment]
I agree that accessibility is important to mention as well, I would also like to ask the stakeholders some more quality attributes that they would want us to take into account, apart from the ones we have already mentioned in section 1.2 (which are privacy, usability, performance and availability), the stakeholders being @labra and @pglez82 or any other teammate that would like to make a contribution, and also I would like to know how to contact Inrupt or Empathy for asking them too (if necessary). 

Finally I have a doubt regarding the design of the quality tree, as it says that it should include links to the scenarios of section 10.2, but I am not sure about how to put the links, and I haven't seen these links in past projects neither.
