### ISSUE TITLE
Workflow for the documentation

### ISSUE THREAD

**Issue by pglez82** [Arquisoft/dede_en2b#22]
Q. What is the supposed workflow? Do we have to create all documentation branches from gh-pages?

_Originally posted by @DiegoMfer in https://github.com/Arquisoft/dede_en2b/issues/4#issuecomment-1034052416_

**Comment by pglez82** [comment]
I move this here, as it is important not no mix issues.

gh-pages branch is a special branch, only used for deploying the documentation into Github Pages. For the documentation you should create a new branch from the master or development branch (if you have one). 

As we said in the labs, you need to think about a branching system to create from the master branch. You have some useful links in the slides of session 1 to decide.

**Comment by CarolinaUniovi** [comment]
To make a pull request once the part of the documentation is finished, should it be done at the specific branch (in my case, "constrains") or at "gh-pages"? Also, when and how should be done "npm run deploy"?

**Comment by pglez82** [comment]
adoc files should go to the constrains branch. gh-pages branch is only for deploying the documentation (the htmls) so it is available in Github Pages, and that is done using `npm run deploy` (after `npm run build` to generate the htmls). So the answer is, you should push your changes to your branch and when finished, create a pull request. You should run `npm run deploy` when you want the version of the doc that you have locally generated to be deployed to github pages. This process can be done several times as needed.
