### ISSUE TITLE
Implement checkout process

### ISSUE THREAD

**Issue by laura-pb** [Arquisoft/dede_en2b#67]
Include a button to checkout in the shopping cart. The checkout process consists of the payment and the shipping cost calculation. Once confirmed, a new order will be added to the database

**Comment by UO277653** [comment]
In the cart view there will be a button to confirm the order, and then you will see the order and the price (as well as shipping cost), then the payment is simulated and then the order is saved in the database.

**Comment by UO277653** [comment]
Hello, @pglez82 , the checkout process is almost complete, to the point where the order is already stored in the databased onced the user has paid, but for some reason it is stored twice, and after tracking the execution of the application in several parts, it seems as if it has something to do with React re-rendering components, or something similar to that, but I am not sure where to look exactly.

**Comment by pglez82** [comment]
My approach will be to debug the application and find out the point where this happens twice. You can find information on how to debug react here:

https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_debugging-react

A very common problem in react (I do not know if it is your case), is the case where a useeffect hook is called multiple times. If that is the case, you should use dependency arrays to control when the effect is called, preventing an operations to be executed multiple times. There is a lot of information on dependency arrays in react online.

Hope that helps.

**Comment by UO277653** [comment]
Hello, I debugged the application some more, and I saw that every piece of code was executed twice, after looking up information for some time on the Internet I found this:
https://stackoverflow.com/questions/61532410/why-my-render-method-is-react-called-twice

And the second answer solved the issue, deleting these two lines in index.tsx

![imagen](https://user-images.githubusercontent.com/79276201/160483713-98cf53bf-e061-42f6-9d60-5abc47a70b40.png)

I leave it here just in case some has the same issue
