### ISSUE TITLE
Deployment of the application

### ISSUE THREAD

**Issue by DiegoMfer** [Arquisoft/dede_en2b#84]
I have to create 3 different docker containers so we can run de application.
- Webapp: already provided
- Restapi: created after building it with the jar file provided by maven
- Mysqldb: pulled from mysql image in dockerhub

Moreover I am in charge of creating the docker-compose files so everything is automated

**Comment by DiegoMfer** [comment]
Problem with the deployment (email sent to the teacher):

Hola, he probado a crear una red en docker-compose como me dijiste, no funciona. He probado a hacer docker-compose up --build y tampoco funciona, aunque me crea las imágenes.

En la aplicación docker de windows me saldrían así:
![image](https://user-images.githubusercontent.com/79276285/160465175-8b5f2364-d1c5-4ca7-8594-7cf0a2230ece.png)

Esto significa que solo se han ejecutado dos. Aunque puedo hacer click en el contenedor de la restapi y ejecutarlo de nuevo. 
Esto lo tengo que hacer para que me ejecute el código en el que muestro las propiedades del fichero, si no no me deja.

Aquí se ve el mensaje con las propiedades después de ejecutar el mensaje:
![image](https://user-images.githubusercontent.com/79276285/160465252-97e17cd0-e966-49f6-8c32-e40f5a07b550.png)


Al menos así sabemos que la url funciona.
Después de hacer esto funciona la aplicación, entonces supongo que será porque todavía no está disponible la base de datos cuando se crea la restapi, pero estoy haciendo malabares más que otra cosa.
![image](https://user-images.githubusercontent.com/79276285/160465344-dfd0573b-e4c7-4ff1-a2af-e505ff519bf9.png)


El jar lo adjunto en github.

**Comment by DiegoMfer** [comment]
Ok, the second option, the one of adding a healthcheck in docker worked. I still got an error but is from java. Thanks.

**Comment by DiegoMfer** [comment]
I have a question, does the application need to be deployed on AWS for monday or it is for the next release on monday? Thanks

**Comment by pglez82** [comment]
I am not sure I understand the question. Next Monday it is the first release day. For this day you must meet all mandatory requirements, including the deployment with the CI system. The deployment platform is up to you, AWS is one option.

**Comment by DiegoMfer** [comment]
Ok, I have another doubt, in the last point of the deployment we have to change the file restapi/server.ts, but since we have it in springboot I don't know if I have to change something, what is the purpose of changing app.use(cors());?

**Comment by DiegoMfer** [comment]
Sorry to ask again but I got an error trying to connect via ssh but i get a connection timeout.
![image](https://user-images.githubusercontent.com/79276285/161118408-d711f659-c15a-45e2-bcf9-fd565e0c4f85.png)

I tried adding  args: "-tt -vvv"  to see the error, as explained here but it didn't work.

**Comment by pglez82** [comment]
> Ok, I have another doubt, in the last point of the deployment we have to change the file restapi/server.ts, but since we have it in springboot I don't know if I have to change something, what is the purpose of changing app.use(cors());?

If it works, you do not need to change anything. Cors is used to control the access to the api. More information here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by DiegoMfer** [comment]
Hello, i get an error about pulling the restapi and the webapp but not having authoritation, the group dede_en2a got the same error so I tried checking their code but I see no difference in it. Moreover, i searched a bit in google about this and the errors that I find are because they are not logging, but in the code the login credentials are already there.
![image](https://user-images.githubusercontent.com/79276285/161306637-014b91d7-e47d-4d03-9e84-99dccb6a4b52.png)



Error:
 
![image](https://user-images.githubusercontent.com/79276285/161306561-8122080d-b827-4ccf-9e3b-ce77d1a40ea0.png)

**Comment by DiegoMfer** [comment]
Hello, I have a problem with connecting the front end to the back end when the application is deployed. I can not connect to the restapi. I have checked that the api endpoint is configured properly and redone it but to no avail. This are de connections urls that are used to accessing the restapi (in local they work because of localhost):
![image](https://user-images.githubusercontent.com/79276285/161378340-4781aa60-cd4b-461d-8962-03a24bc54b7b.png)
Moreover I have tried to changing the name of the connection to the name of the container, but this does not. I have also tried what is here : https://stackoverflow.com/questions/66588361/calling-rest-api-through-docker-container

**Comment by DiegoMfer** [comment]
Hello, I have a problem with the restapi, the container is not deployed over ssh. I wanted to check the logs of the containers in the vm in aws but since there is no restapi deployed i can't.
Thanks in advance.

**Comment by DiegoMfer** [comment]
Hello, I have a mistake when uncommenting the part of asw2122.yml on line 45, it gives me an syntax error even if the line is commented
![image](https://user-images.githubusercontent.com/79276285/164047138-2f36b68d-1945-4c3a-bc64-a81927266b44.png)
I have it as in your repository, but the mistake only goes away when I remove the tests
![image](https://user-images.githubusercontent.com/79276285/164082039-da355f8a-7c3f-449e-8a0c-253e121680f9.png)
I have tried multiple times

**Comment by pglez82** [comment]
No need to ask me in multiple issues with the same information. You have the answer in the other issue #130 .

**Comment by DiegoMfer** [comment]
Sorry, I didn't realized.

**Comment by pglez82** [comment]
It this issue solved. Maybe it can be closed?
